from abc import ABC, abstractmethod
from typing import List, Union

from happysimulator.events.event import Event
from happysimulator.utils.instant import Instant

class EventProvider(ABC):
    """
    Abstract interface for entities that create the specific payload events 
    generated by a Source.
    """
    @abstractmethod
    def get_events(self, time: Instant) -> Union[Event, List[Event]]:
        """
        Generates the list of events that should occur at the given time.
        """
        pass