"""happy-simulator: A discrete-event simulation library for Python."""

__version__ = "0.1.3"

import logging

# Library best practice: silent by default
# Users must explicitly enable logging using the configure functions below
logging.getLogger("happysimulator").addHandler(logging.NullHandler())

# Core simulation types
from happysimulator.core import (
    CallbackEntity,
    Clock,
    Entity,
    Event,
    Instant,
    NullEntity,
    SimFuture,
    any_of,
    all_of,
    Simulation,
    Simulatable,
    simulatable,
    ClockModel,
    FixedSkew,
    LinearDrift,
    NodeClock,
    LamportClock,
    VectorClock,
    HLCTimestamp,
    HybridLogicalClock,
    SimulationControl,
    SimulationState,
    BreakpointContext,
    TimeBreakpoint,
    EventCountBreakpoint,
    ConditionBreakpoint,
    MetricBreakpoint,
    EventTypeBreakpoint,
)
from happysimulator.core.temporal import Duration

# Load generation
from happysimulator.load import (
    ConstantArrivalTimeProvider,
    ConstantRateProfile,
    DistributedFieldProvider,
    EventProvider,
    LinearRampProfile,
    PoissonArrivalTimeProvider,
    Profile,
    Source,
    SpikeProfile,
)

# Components
from happysimulator.components import (
    Counter,
    FIFOQueue,
    LIFOQueue,
    PriorityQueue,
    Queue,
    QueueDriver,
    QueuedResource,
    RandomRouter,
    RateLimiterPolicy,
    RateLimitedEntity,
    RateLimitedEntityStats,
    Sink,
    TokenBucketPolicy,
    LeakyBucketPolicy,
    SlidingWindowPolicy,
    FixedWindowPolicy,
    AdaptivePolicy,
    RateAdjustmentReason,
    RateSnapshot,
    Inductor,
    InductorStats,
    Resource,
    Grant,
    ResourceStats,
    Network,
    NetworkLink,
    Partition,
    LinkStats,
    local_network,
    datacenter_network,
    cross_region_network,
    internet_network,
    satellite_network,
    lossy_network,
    slow_network,
    mobile_3g_network,
    mobile_4g_network,
    EventLog,
    EventLogStats,
    Record,
    TimeRetention,
    SizeRetention,
    ConsumerGroup,
    ConsumerGroupStats,
    RangeAssignment,
    RoundRobinAssignment,
    StickyAssignment,
    StreamProcessor,
    StreamProcessorStats,
    TumblingWindow,
    SlidingWindow,
    SessionWindow,
    LateEventPolicy,
)

# Microservice patterns
from happysimulator.components.microservice import (
    IdempotencyStore,
    Sidecar,
    OutboxRelay,
    Saga,
    SagaStep,
    SagaState,
    APIGateway,
    RouteConfig,
)

# Distributions
from happysimulator.distributions import (
    ConstantLatency,
    ExponentialLatency,
    PercentileFittedLatency,
    UniformDistribution,
    ValueDistribution,
    ZipfDistribution,
)

# Instrumentation
from happysimulator.instrumentation import (
    BucketedData,
    Data,
    EntitySummary,
    LatencyTracker,
    Probe,
    QueueStats,
    SimulationSummary,
    ThroughputTracker,
)

# Sketching algorithms
from happysimulator.sketching import (
    TopK,
    CountMinSketch,
    TDigest,
    HyperLogLog,
    BloomFilter,
    ReservoirSampler,
    FrequencyEstimate,
    MerkleTree,
    KeyRange,
)

# Consensus & Coordination
from happysimulator.components.consensus import (
    Log,
    LogEntry,
    PhiAccrualDetector,
    KVStateMachine,
    MembershipProtocol,
    MemberState,
    BullyStrategy,
    RingStrategy,
    RandomizedStrategy,
    LeaderElection,
    PaxosNode,
    Ballot,
    MultiPaxosNode,
    FlexiblePaxosNode,
    RaftNode,
    RaftState,
    DistributedLock,
    LockGrant,
)

# Sketching entity wrappers
from happysimulator.components.sketching import (
    SketchCollector,
    TopKCollector,
    QuantileEstimator,
)

# Storage Engine Internals
from happysimulator.components.storage import (
    SSTable,
    WriteAheadLog,
    Memtable,
    LSMTree,
    BTree,
    TransactionManager,
    IsolationLevel,
    SizeTieredCompaction,
    LeveledCompaction,
    FIFOCompaction,
    SyncEveryWrite,
    SyncPeriodic,
    SyncOnBatch,
)

# Infrastructure Primitives
from happysimulator.components.infrastructure import (
    DiskIO,
    DiskIOStats,
    DiskProfile,
    HDD,
    SSD,
    NVMe,
    PageCache,
    PageCacheStats,
    CPUScheduler,
    CPUSchedulerStats,
    FairShare,
    PriorityPreemptive,
    GarbageCollector,
    GCStats,
    StopTheWorld,
    ConcurrentGC,
    GenerationalGC,
    TCPConnection,
    TCPStats,
    AIMD,
    Cubic,
    BBR,
    DNSResolver,
    DNSRecord,
    DNSStats,
)

# Scheduling
from happysimulator.components.scheduling import (
    JobDefinition,
    JobScheduler,
    JobSchedulerStats,
    JobState,
    WorkerStats,
    WorkStealingPool,
    WorkStealingPoolStats,
)

# Deployment
from happysimulator.components.deployment import (
    AutoScaler,
    AutoScalerStats,
    ScalingPolicy,
    TargetUtilization,
    StepScaling,
    QueueDepthScaling,
    ScalingEvent,
    RollingDeployer,
    RollingDeployerStats,
    DeploymentState,
    CanaryDeployer,
    CanaryDeployerStats,
    CanaryStage,
    CanaryState,
    MetricEvaluator,
    ErrorRateEvaluator,
    LatencyEvaluator,
)

# Behavior
from happysimulator.components.behavior import (
    TraitSet,
    PersonalityTraits,
    NormalTraitDistribution,
    UniformTraitDistribution,
    AgentState,
    Memory,
    Choice,
    DecisionContext,
    UtilityModel,
    Rule,
    RuleBasedModel,
    BoundedRationalityModel,
    SocialInfluenceModel,
    CompositeModel,
    Agent,
    Relationship,
    SocialGraph,
    BehaviorEnvironment,
    DeGrootModel,
    BoundedConfidenceModel,
    VoterModel,
    DemographicSegment,
    Population,
    broadcast_stimulus,
    targeted_stimulus,
    price_change,
    policy_announcement,
    influence_propagation,
    AgentStats,
    PopulationStats,
    EnvironmentStats,
)

# CRDTs
from happysimulator.components.crdt import (
    CRDT,
    GCounter,
    PNCounter,
    LWWRegister,
    ORSet,
    CRDTStore,
    CRDTStoreStats,
)

# Industrial simulation components
from happysimulator.components.industrial import (
    BalkingQueue,
    RenegingQueuedResource,
    ConveyorBelt,
    InspectionStation,
    BatchProcessor,
    Shift,
    ShiftSchedule,
    ShiftedServer,
    BreakdownScheduler,
    InventoryBuffer,
    AppointmentScheduler,
    ConditionalRouter,
    PerishableInventory,
    PooledCycleResource,
    GateController,
    SplitMerge,
    PreemptibleResource,
    PreemptibleGrant,
)

# Fault injection
from happysimulator.faults import FaultSchedule

# Logging configuration utilities
from happysimulator.logging_config import (
    configure_from_env,
    disable_logging,
    enable_console_logging,
    enable_file_logging,
    enable_json_file_logging,
    enable_json_logging,
    enable_timed_file_logging,
    set_level,
    set_module_level,
)

__all__ = [
    # Package metadata
    "__version__",
    # Core
    "Simulation",
    "Event",
    "Entity",
    "CallbackEntity",
    "NullEntity",
    "Instant",
    "Duration",
    "Clock",
    "Simulatable",
    "simulatable",
    # SimFuture
    "SimFuture",
    "any_of",
    "all_of",
    # Node clocks
    "ClockModel",
    "FixedSkew",
    "LinearDrift",
    "NodeClock",
    # Logical clocks
    "LamportClock",
    "VectorClock",
    "HLCTimestamp",
    "HybridLogicalClock",
    # Simulation control
    "SimulationControl",
    "SimulationState",
    "BreakpointContext",
    "TimeBreakpoint",
    "EventCountBreakpoint",
    "ConditionBreakpoint",
    "MetricBreakpoint",
    "EventTypeBreakpoint",
    # Load
    "Source",
    "EventProvider",
    "Profile",
    "ConstantRateProfile",
    "LinearRampProfile",
    "SpikeProfile",
    "ConstantArrivalTimeProvider",
    "PoissonArrivalTimeProvider",
    # Components
    "Counter",
    "Queue",
    "QueueDriver",
    "QueuedResource",
    "FIFOQueue",
    "LIFOQueue",
    "PriorityQueue",
    "RandomRouter",
    "Sink",
    # Rate limiters
    "RateLimiterPolicy",
    "RateLimitedEntity",
    "RateLimitedEntityStats",
    "TokenBucketPolicy",
    "LeakyBucketPolicy",
    "SlidingWindowPolicy",
    "FixedWindowPolicy",
    "AdaptivePolicy",
    "RateAdjustmentReason",
    "RateSnapshot",
    "Inductor",
    "InductorStats",
    # Shared resources
    "Resource",
    "Grant",
    "ResourceStats",
    # Network
    "Network",
    "NetworkLink",
    "Partition",
    "LinkStats",
    "local_network",
    "datacenter_network",
    "cross_region_network",
    "internet_network",
    "satellite_network",
    "lossy_network",
    "slow_network",
    "mobile_3g_network",
    "mobile_4g_network",
    # Streaming
    "EventLog",
    "EventLogStats",
    "Record",
    "TimeRetention",
    "SizeRetention",
    "ConsumerGroup",
    "ConsumerGroupStats",
    "RangeAssignment",
    "RoundRobinAssignment",
    "StickyAssignment",
    "StreamProcessor",
    "StreamProcessorStats",
    "TumblingWindow",
    "SlidingWindow",
    "SessionWindow",
    "LateEventPolicy",
    # Distributions
    "ConstantLatency",
    "ExponentialLatency",
    "PercentileFittedLatency",
    "ZipfDistribution",
    "UniformDistribution",
    "ValueDistribution",
    # Load providers
    "DistributedFieldProvider",
    # Instrumentation
    "BucketedData",
    "Data",
    "EntitySummary",
    "LatencyTracker",
    "Probe",
    "QueueStats",
    "SimulationSummary",
    "ThroughputTracker",
    # Sketching algorithms
    "TopK",
    "CountMinSketch",
    "TDigest",
    "HyperLogLog",
    "BloomFilter",
    "ReservoirSampler",
    "FrequencyEstimate",
    "MerkleTree",
    "KeyRange",
    # Sketching entity wrappers
    "SketchCollector",
    "TopKCollector",
    "QuantileEstimator",
    # Microservice patterns
    "IdempotencyStore",
    "Sidecar",
    "OutboxRelay",
    "Saga",
    "SagaStep",
    "SagaState",
    "APIGateway",
    "RouteConfig",
    # Consensus & Coordination
    "Log",
    "LogEntry",
    "PhiAccrualDetector",
    "KVStateMachine",
    "MembershipProtocol",
    "MemberState",
    "BullyStrategy",
    "RingStrategy",
    "RandomizedStrategy",
    "LeaderElection",
    "PaxosNode",
    "Ballot",
    "MultiPaxosNode",
    "FlexiblePaxosNode",
    "RaftNode",
    "RaftState",
    "DistributedLock",
    "LockGrant",
    # Storage Engine Internals
    "SSTable",
    "WriteAheadLog",
    "Memtable",
    "LSMTree",
    "BTree",
    "TransactionManager",
    "IsolationLevel",
    "SizeTieredCompaction",
    "LeveledCompaction",
    "FIFOCompaction",
    "SyncEveryWrite",
    "SyncPeriodic",
    "SyncOnBatch",
    # Infrastructure Primitives
    "DiskIO",
    "DiskIOStats",
    "DiskProfile",
    "HDD",
    "SSD",
    "NVMe",
    "PageCache",
    "PageCacheStats",
    "CPUScheduler",
    "CPUSchedulerStats",
    "FairShare",
    "PriorityPreemptive",
    "GarbageCollector",
    "GCStats",
    "StopTheWorld",
    "ConcurrentGC",
    "GenerationalGC",
    "TCPConnection",
    "TCPStats",
    "AIMD",
    "Cubic",
    "BBR",
    "DNSResolver",
    "DNSRecord",
    "DNSStats",
    # Scheduling
    "JobDefinition",
    "JobScheduler",
    "JobSchedulerStats",
    "JobState",
    "WorkerStats",
    "WorkStealingPool",
    "WorkStealingPoolStats",
    # Deployment
    "AutoScaler",
    "AutoScalerStats",
    "ScalingPolicy",
    "TargetUtilization",
    "StepScaling",
    "QueueDepthScaling",
    "ScalingEvent",
    "RollingDeployer",
    "RollingDeployerStats",
    "DeploymentState",
    "CanaryDeployer",
    "CanaryDeployerStats",
    "CanaryStage",
    "CanaryState",
    "MetricEvaluator",
    "ErrorRateEvaluator",
    "LatencyEvaluator",
    # CRDTs
    "CRDT",
    "GCounter",
    "PNCounter",
    "LWWRegister",
    "ORSet",
    "CRDTStore",
    "CRDTStoreStats",
    # Behavior
    "TraitSet",
    "PersonalityTraits",
    "NormalTraitDistribution",
    "UniformTraitDistribution",
    "AgentState",
    "Memory",
    "Choice",
    "DecisionContext",
    "UtilityModel",
    "Rule",
    "RuleBasedModel",
    "BoundedRationalityModel",
    "SocialInfluenceModel",
    "CompositeModel",
    "Agent",
    "Relationship",
    "SocialGraph",
    "BehaviorEnvironment",
    "DeGrootModel",
    "BoundedConfidenceModel",
    "VoterModel",
    "DemographicSegment",
    "Population",
    "broadcast_stimulus",
    "targeted_stimulus",
    "price_change",
    "policy_announcement",
    "influence_propagation",
    "AgentStats",
    "PopulationStats",
    "EnvironmentStats",
    # Industrial simulation components
    "BalkingQueue",
    "RenegingQueuedResource",
    "ConveyorBelt",
    "InspectionStation",
    "BatchProcessor",
    "Shift",
    "ShiftSchedule",
    "ShiftedServer",
    "BreakdownScheduler",
    "InventoryBuffer",
    "AppointmentScheduler",
    "ConditionalRouter",
    "PerishableInventory",
    "PooledCycleResource",
    "GateController",
    "SplitMerge",
    "PreemptibleResource",
    "PreemptibleGrant",
    # Fault injection
    "FaultSchedule",
    # Logging configuration
    "configure_from_env",
    "disable_logging",
    "enable_console_logging",
    "enable_file_logging",
    "enable_json_file_logging",
    "enable_json_logging",
    "enable_timed_file_logging",
    "set_level",
    "set_module_level",
]
